---
title: "Heat Resiliency in Arizona"
---

# The Problem Statement

Climate change represents a profound crisis for the nation, making natural disasters
more frequent, more intense, and more destructive. In 2020 alone, there were 22 weather and climate disaster events, with total losses exceeding $1 billion across the U.S. In comparison, the previous record set in both 2011 and 2017 was 16 disasters. Emergency managers in communities across the country face increasing demands generated by more extreme and frequent disasters — from wildfires and coastal storms to inland flooding – as well as climate-related emergencies such as drought and extreme heat.

The growing severity of disasters increases the time it takes for communities to recover — a process that can be further complicated by repeat events in areas already struggling to bounce back. These cascading and compounding impacts, propelled by climate change, pose the greatest risk to our communal and nationwide resilience. Natural disasters often disproportionately affect people in underserved communities where weakened infrastructure, fewer resources, and less support to invest in hazard mitigation can compound a disaster’s impact.

To help confront these threats, we must enhance the nation’s ability to anticipate, prepare for, and adapt to future climate conditions. This starts with fostering a common understanding of how climate change will reshape emergency management at both the community and household level, and includes building better resources and tools to drive understanding of future risk and enhance a community’s ability to act.

While risk maps and climate projection data for specific hazards exist, we do not yet have widely available tools to help communities and individuals prioritize mitigation strategies based on cost, impact, and other factors.

# The Proposed Solution

This website presents both curated and data-drive information on Heat Resilience and Housing Stability in the state of Arizona. We see an increased number of heat wave days every year in our state. That combined with housing problems, when utilities can be expensive, especially in non-insulated mobile homes, can cause emergencies. 




